#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME"/nixpkgs

# Create symlinks for existing configurations
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
ln -sf "$PWD/.zshrc" "$HOME/.zshrc"


# Install Nix packages from config.nix
nix-env -iA nixpkgs.myPackages

echo "All packages have been installed."

# Set up completions

mkdir -p "$HOME/.zfunc"
flux completion zsh > $HOME/.zfunc/_flux
kubectl completion zsh > $HOME/.zfunc/_kubectl
helm completion zsh > $HOME/.zfunc/_helm

echo "Setup complete. Zsh configuration files have been downloaded and set up."


